language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  #- php -n php-cs-fixer.phar fix -v --dry-run --level=all src
  - cp ~/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - php vendor/bin/phpunit -c travis.phpunit.xml
  - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

after_script:
  - php composer/bin/coveralls -v --exclude-no-stmt

